name: CI

on:
  pull_request:
    branches: [ "**" ]
  push:
    branches: [ main ]

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Enable Corepack
        run: corepack enable

      - name: Activate pnpm 9
        run: corepack prepare pnpm@9 --activate

      - name: Verify pnpm
        run: pnpm --version

      - name: Install dependencies
        run: pnpm install -w --frozen-lockfile

      - name: Lint
        run: pnpm -w lint

      - name: Typecheck
        run: pnpm -w typecheck
